name: UI Automation Smoke Tests
env:
  TEST_BROWSER: 'chrome'
  TEST_ENVIRONMENT: 'staging'
on:
  push:
    branches:
      - main

jobs:
  run_tests_macos:

    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@latest
      
      - name: check old value 
        run: |
            date
      - name: new value
        run: |
           system_profiler SPDisplaysDataType | grep Resolution
